/*
 * FinancialStatus.java
 *
 * Created on May 29, 2008, 5:42 PM
 */


import java.awt.print.PrinterException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * 
 * @author kfryauff
 */
public class FinancialStatus extends javax.swing.JFrame {

	/** Creates new form FinancialStatus */
	public FinancialStatus() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		openBtn = new javax.swing.JButton();
		returnBtn = new javax.swing.JButton();
		exitBtn = new javax.swing.JButton();
		printPageBtn = new javax.swing.JButton();
		innerInfoPanel = new javax.swing.JPanel();
		tableScrollPanel = new javax.swing.JScrollPane();
		inventoryTable = new javax.swing.JTable();
		amntTxtField = new javax.swing.JTextField();
		txtField = new javax.swing.JTextField();
		titlePanel = new javax.swing.JPanel();
		titleLbl = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(204, 255, 255));
		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(
				new java.awt.Color(255, 153, 204), 3));

		openBtn.setText("OPEN");
		openBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				openBtnActionPerformed(evt);
			}
		});

		returnBtn.setText("Back To Main");
		returnBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				returnBtnActionPerformed(evt);
			}
		});

		exitBtn.setText("Exit");
		exitBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitBtnActionPerformed(evt);
			}
		});

		printPageBtn.setText("PRINT PAGE");
		printPageBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				printPageBtnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																openBtn,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																95,
																Short.MAX_VALUE)
														.addComponent(
																returnBtn,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																exitBtn,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																95,
																Short.MAX_VALUE)
														.addComponent(
																printPageBtn,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																95,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												openBtn,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												38,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												printPageBtn,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												38,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												286, Short.MAX_VALUE)
										.addComponent(returnBtn)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(exitBtn).addGap(18, 18,
												18)));

		innerInfoPanel.setBackground(new java.awt.Color(204, 255, 255));
		innerInfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(
				new java.awt.Color(255, 153, 204), 3));

		inventoryTable.setAutoCreateRowSorter(true);
		inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null,
						null, null } }, new String[] { "Item Name", "Size",
						"Color", "Gender", "Price", "Amount", "Description",
						"Condition", "Popularity" }) {
			Class[] types = new Class[] { java.lang.String.class,
					java.lang.String.class, java.lang.String.class,
					java.lang.String.class, java.lang.Object.class,
					java.lang.Object.class, java.lang.String.class,
					java.lang.String.class, java.lang.String.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		tableScrollPanel.setViewportView(inventoryTable);

		amntTxtField.setEditable(false);

		txtField.setEditable(false);
		txtField.setText("Total Amount Recieved:");

		javax.swing.GroupLayout innerInfoPanelLayout = new javax.swing.GroupLayout(
				innerInfoPanel);
		innerInfoPanel.setLayout(innerInfoPanelLayout);
		innerInfoPanelLayout
				.setHorizontalGroup(innerInfoPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								innerInfoPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												innerInfoPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																innerInfoPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				txtField,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				150,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				amntTxtField,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				81,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				12,
																				12,
																				12))
														.addComponent(
																tableScrollPanel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																856,
																Short.MAX_VALUE))
										.addContainerGap()));
		innerInfoPanelLayout
				.setVerticalGroup(innerInfoPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								innerInfoPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												tableScrollPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												402,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												innerInfoPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																txtField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																amntTxtField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()));

		titlePanel.setBackground(new java.awt.Color(204, 255, 255));
		titlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(
				new java.awt.Color(255, 153, 204), 3));

		titleLbl.setBackground(new java.awt.Color(204, 255, 255));
		titleLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		titleLbl.setText("Financial Status");

		javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(
				titlePanel);
		titlePanel.setLayout(titlePanelLayout);
		titlePanelLayout
				.setHorizontalGroup(titlePanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								titlePanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												titleLbl,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												983, Short.MAX_VALUE)
										.addContainerGap()));
		titlePanelLayout.setVerticalGroup(titlePanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 36,
				Short.MAX_VALUE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 1009, Short.MAX_VALUE)
						.addComponent(titlePanel,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												innerInfoPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(
												jPanel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 508, Short.MAX_VALUE)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												titlePanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanel1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																innerInfoPanel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																460,
																javax.swing.GroupLayout.PREFERRED_SIZE))));

		pack();
	}// </editor-fold>

	private void addRemoveRow(int x) {
		// if (rowNum >= inventoryTable.getRowCount()) {
		Object[][] newTable = new Object[rowNum + x][9];
		int length = 0;
		if (x < 0) {
			length = newTable.length;
		} else {
			length = tableArray.length;
		}
		for (int i = 0; i < length; i++) {
			for (int j = 0; j < tableArray[0].length; j++) {
				newTable[i][j] = tableArray[i][j];
			}
		}
		tableArray = newTable;
		drawNewTable();
		// setRowCount(newTable, inventoryTable.getRowCount());
		// }
		rowNum += x;
	}

	private void drawNewTable() {
		inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
				tableArray, new String[] { "Item Name", "Size", "Color",
						"Gender", "Price", "Amount", "Description",
						"Condition", "Popularity" }));
	}

	private int obtainTotal() {
		for (int i = 0; i < rowNum; i++) {
			if (tableArray[i][7].toString().equalsIgnoreCase("sold")) {
				String str = tableArray[i][4].toString();
				String str2 = tableArray[i][5].toString().trim();
				if (str.charAt(0) == '$') {
					str = str.substring(1).trim();
				}
				try {
					double price = Double.parseDouble(str);
					int amnt = Integer.parseInt(str2);
					totalAmnt += (price * amnt);
				} catch (java.lang.StringIndexOutOfBoundsException e) {
					WarningJDialog warning = new WarningJDialog(this, true);
					warning.printMessage("Please Choose a difference file");
					warning.setVisible(true);
					return 0;
				}
			}
		}
		return 1;
	}

	private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int flag = 1;
		do {
			File file = MessageUtil.getPath(inventoryTable, MessageUtil.OPEN,
					MessageUtil.FILES_ONLY);
			if (file == null) {
				return;
			}
			BufferedReader input = null;
			try {
				input = new BufferedReader(new FileReader(file));
			} catch (FileNotFoundException e) {
				e.printStackTrace();
			}

			String line;
			tableArray = new Object[1][9];
			rowNum = 0;
			int lineNum = 0;
			try {
				while ((line = input.readLine()) != null) {
					lineNum++;
					addRemoveRow(1); // adds one row to tableArray (and to
										// table)

					int start = 0;
					int end = line.indexOf("||", start);

					for (int i = 0; i < tableArray[0].length; i++) {
						String word = line.substring(start, end);
						System.out.println("row: " + rowNum + "  i: " + i
								+ " word: " + word + " \t end: " + end
								+ " tbl length: " + tableArray.length + ", "
								+ tableArray[0].length);
						tableArray[rowNum - 1][i] = word.trim();
						start = end + 2;
						end = line.indexOf("||", start);
					}

				}
				input.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
			drawNewTable();
			flag = obtainTotal();
		} while (flag == 0);
		amntTxtField.setText(priceForm.format(totalAmnt));
	}

	private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.setVisible(false);
		new mainM().setVisible(true);
	}

	private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		WarningJDialog warning = new WarningJDialog(this, true);
		warning.printExitMessage("PROGRAM WILL NOW CLOSE... \n\n GOOD BYE!!",
				"CANCEL");
		warning.setVisible(true);
		System.exit(0);
	}

	private void printPageBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try {
			inventoryTable.print();
		} catch (PrinterException ex) {
			Logger.getLogger(FinancialStatus.class.getName()).log(Level.SEVERE,
					null, ex);
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new

		Runnable() {

			public void run() {
				new FinancialStatus().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JTextField amntTxtField;
	private javax.swing.JButton exitBtn;
	private javax.swing.JPanel innerInfoPanel;
	public static javax.swing.JTable inventoryTable;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JButton openBtn;
	private javax.swing.JButton printPageBtn;
	private javax.swing.JButton returnBtn;
	private javax.swing.JScrollPane tableScrollPanel;
	private javax.swing.JLabel titleLbl;
	private javax.swing.JPanel titlePanel;
	private javax.swing.JTextField txtField;
	// End of variables declaration
	private int rowNum = 0;
	private Object[][] tableArray = new Object[][] { { null, null, null, null,
			null, null, null, null, null } };
	private double totalAmnt = 0;
	private DecimalFormat priceForm = new DecimalFormat("$####.00");
}
