/**
 * mainM.java
 * @author TEAM LEGENDARY.
 * @client BabyCakes
 * 
 * Created on May 6, 2008, 4:59 AM
 * Updated on 6 May 2008 ====== Outline completed
 * 								Exit Button functionality completed
 * Updated on 7 May 2008 ====== Inventory Panel Completed
 * Updated on 12 May 2008 ===== Changed from using separate panels to use of separate Frames
 * 								Completed
 */


import javax.swing.JFrame;

/**
 * 
 * @author kfryauff
 * mainM makes calls to all other classes within action events of a particular button
 *
 */
public class mainM extends javax.swing.JFrame {

	/** Creates new form mainM */
	public mainM() {
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		/*  Initializes all panels, buttons, components, etc
		 * 
		 */
		
		titlePanel = new javax.swing.JPanel();
		titleLbl = new javax.swing.JLabel();
		buttonPanel = new javax.swing.JPanel();
		exitBtn = new javax.swing.JButton();
		financialStatusBtn = new javax.swing.JButton();
		editInventoryBtn = new javax.swing.JButton();
		toDoListBtn = new javax.swing.JButton();
		viewInventoryBtn = new javax.swing.JButton();
		infoPanel = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 153, 204));

		titlePanel.setBackground(new java.awt.Color(204, 255, 255));
		titlePanel.setBorder(new javax.swing.border.LineBorder(
				new java.awt.Color(255, 153, 204), 3, true));

		titleLbl.setBackground(new java.awt.Color(102, 255, 255));
		titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		titleLbl
				.setIcon(new javax.swing.ImageIcon(
						"C:\\Users\\owner\\Documents\\Krista's Files\\10th grade PHS\\Quarter4\\CS\\Title.jpg")); // NOI18N

		javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(
				titlePanel);
		titlePanel.setLayout(titlePanelLayout);
		titlePanelLayout
				.setHorizontalGroup(titlePanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								titlePanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												titleLbl,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												701, Short.MAX_VALUE)
										.addContainerGap()));
		titlePanelLayout.setVerticalGroup(titlePanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
				Short.MAX_VALUE));

		buttonPanel.setBackground(new java.awt.Color(204, 255, 255));
		buttonPanel.setBorder(new javax.swing.border.LineBorder(
				new java.awt.Color(255, 153, 204), 3, true));

		exitBtn.setText("EXIT");
		exitBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitBtnActionPerformed(evt);
			}
		});

		financialStatusBtn.setText("Financial Status");
		financialStatusBtn
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						financialStatusBtnActionPerformed(evt);
					}
				});

		editInventoryBtn.setText("Edit Inventory");
		editInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				editInventoryBtnActionPerformed(evt);
			}
		});

		toDoListBtn.setText("To-Do List");
		toDoListBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				toDoListBtnActionPerformed(evt);
			}
		});

		viewInventoryBtn.setText("View Inventory");
		viewInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				viewInventoryBtnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(
				buttonPanel);
		buttonPanel.setLayout(buttonPanelLayout);
		buttonPanelLayout
				.setHorizontalGroup(buttonPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								buttonPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												buttonPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																editInventoryBtn,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																119,
																Short.MAX_VALUE)
														.addComponent(
																exitBtn,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																119,
																Short.MAX_VALUE)
														.addComponent(
																toDoListBtn,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																119,
																Short.MAX_VALUE)
														.addComponent(
																viewInventoryBtn,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																119,
																Short.MAX_VALUE)
														.addComponent(
																financialStatusBtn,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																119,
																Short.MAX_VALUE))
										.addContainerGap()));
		buttonPanelLayout
				.setVerticalGroup(buttonPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								buttonPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(editInventoryBtn)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(viewInventoryBtn)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(toDoListBtn)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(financialStatusBtn)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												257, Short.MAX_VALUE)
										.addComponent(exitBtn)
										.addContainerGap()));

		infoPanel.setBackground(new java.awt.Color(204, 255, 255));
		infoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(
				new java.awt.Color(255, 153, 204), 3));

		jLabel1
				.setIcon(new javax.swing.ImageIcon(
						"C:\\Users\\owner\\Documents\\Krista's Files\\10th grade PHS\\Quarter4\\CS\\babycakes_introImage.jpg")); // NOI18N

		javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(
				infoPanel);
		infoPanel.setLayout(infoPanelLayout);
		infoPanelLayout.setHorizontalGroup(infoPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel1));
		infoPanelLayout.setVerticalGroup(infoPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel1));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(titlePanel,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												buttonPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												infoPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												titlePanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																buttonPanel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																infoPanel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))));

		pack();
	}// </editor-fold>

	private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void editInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		editInventory.setVisible(true);
		this.setVisible(false);

	}

	private void viewInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		viewInventory.setVisible(true);
		this.setVisible(false);
	}

	private void toDoListBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		todo.setVisible(true);
		this.setVisible(false);
	}

	private void financialStatusBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		finaStat.setVisible(true);
		this.setVisible(false);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new mainM().setVisible(true);
			}
		});
	}

	// Variables declaration
	private javax.swing.JPanel buttonPanel;
	private javax.swing.JButton editInventoryBtn;
	private javax.swing.JButton exitBtn;
	private javax.swing.JButton financialStatusBtn;
	private javax.swing.JPanel infoPanel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel titleLbl;
	private javax.swing.JPanel titlePanel;
	private javax.swing.JButton toDoListBtn;
	private javax.swing.JButton viewInventoryBtn;
	private javax.swing.JFrame editInventory = new Inventory();
	private javax.swing.JFrame viewInventory = new ViewInventory();
	private javax.swing.JFrame todo = new ToDoList();
	private javax.swing.JFrame finaStat = new FinancialStatus();
	// End of variables declaration
}
